linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - exhaustive
    - godot
    - noctx
    - unconvert
    - unparam
    - unused
    - misspell
    - revive

linters-settings:
  godot:
    scope: declarations
    period: true
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - godot

run:
  timeout: 5m
